name: untitled1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: lib/ui/fonts/SFProText/SFProText_Regular.ttf
        - asset: lib/ui/fonts/SFProDisplay/SFProText_Medium.ttf
        - asset: lib/ui/fonts/SFProText/SFProText_Bold.ttf
          weight: 800
    - family: SF Pro Display
      fonts:
        - asset: lib/ui/fonts/SFProDisplay/SFProDisplay_Regular.otf
        - asset: lib/ui/fonts/SFProDisplay/SFProDisplay_Bold.otf
          weight: 700
